Repository emscripten-forge/recipes, pull requests merged in 2025-07, with the labels that each got.

#2489 Add zenoh-pico (3.1.45)
  ci_env.yml
  conda_build_config.yaml
  emci/constants.py
  pixi.toml
  recipes/recipes_emscripten/micro-cdr/build.sh
  recipes/recipes_emscripten/micro-cdr/recipe.yaml
  recipes/recipes_emscripten/zenoh-pico/build.sh
  recipes/recipes_emscripten/zenoh-pico/recipe.yaml
Labels: 3.1.45

#2495 Fix issue with conda_build_config
  .github/workflows/build_recipes.yaml
  ci_env.yml
  emci/constants.py
  variant.yaml
Labels: bug, 3.1.45

#2522 Iterate over a larger version range
  emci/bot/next_version.py
Labels: bot
