Repository emscripten-forge/recipes, pull requests merged in 2025-06, with the labels that each got.

#2369 Update xeus-r from 0.6.0 to 0.7.0
  recipes/recipes_emscripten/xeus-r/recipe.yaml
Labels: R

#2372 Pin r-base version in xeus-r
  recipes/recipes_emscripten/xeus-r/recipe.yaml
Labels: R

#2374 Add recipe for git2cpp
  recipes/recipes_emscripten/git2cpp/build.sh
  recipes/recipes_emscripten/git2cpp/emscripten.meson.cross
  recipes/recipes_emscripten/git2cpp/recipe.yaml
Labels: enhancement

#2416 Add recipe for `less` to run in `cockle`
  recipes/recipes_emscripten/less/build.sh
  recipes/recipes_emscripten/less/recipe.yaml
Labels: enhancement

#2418 Use default value for LDFLAGS for llvm recipe
  recipes/recipes_emscripten/llvm/build.sh
  recipes/recipes_emscripten/llvm/recipe.yaml
Labels: Automerge

#2443 Handle recipes with multiple urls [bot]
  emci/bot/bump_recipes_versions.py
Labels: bot

#2450 Minor fix in cross-python
  recipes/recipes/cross-python_emscripten-wasm32/activate.sh
  recipes/recipes/cross-python_emscripten-wasm32/recipe.yaml
Labels: bug

#2454 Ensure version is a string
  emci/bot/bump_recipes_versions.py
Labels: bug, bot

#2466 [bot] Handle recipes with source paths
  emci/bot/bump_recipes_versions.py
Labels: bot

#2476 Minor bot improvements
  emci/bot/bump_recipes_versions.py
Labels: bot
