Repository emscripten-forge/recipes, pull requests merged in 2025-01, with the labels that each got.

#1498 Add r-dplyr
  recipes/recipes_emscripten/r-dplyr/recipe.yaml
Labels: R

#1500 Add r-tidyr
  recipes/recipes_emscripten/r-tidyr/recipe.yaml
Labels: R

#1501 Add r-hexbin
  recipes/recipes_emscripten/r-hexbin/GPL-2
  recipes/recipes_emscripten/r-hexbin/build.sh
  recipes/recipes_emscripten/r-hexbin/recipe.yaml
Labels: R

#1502 Add r-rcpp
  recipes/recipes_emscripten/r-rcpp/GPL-2
  recipes/recipes_emscripten/r-rcpp/patches/0001-Disable-demangler.patch
  recipes/recipes_emscripten/r-rcpp/recipe.yaml
Labels: R

#1503 Add r-later
  recipes/recipes_emscripten/r-later/build.sh
  recipes/recipes_emscripten/r-later/patches/0001-Do-not-link-with-atomic-lib.patch
  recipes/recipes_emscripten/r-later/patches/exceptions_impl.h
  recipes/recipes_emscripten/r-later/recipe.yaml
Labels: R

#1504 Add r-promises
  recipes/recipes_emscripten/r-promises/build.sh
  recipes/recipes_emscripten/r-promises/patches/exceptions_impl.h
  recipes/recipes_emscripten/r-promises/recipe.yaml
Labels: R

#1505 Add r-lazyeval
  recipes/recipes_emscripten/r-lazyeval/GPL-3
  recipes/recipes_emscripten/r-lazyeval/recipe.yaml
Labels: R

#1508 Add r-askpass
  recipes/recipes_emscripten/r-askpass/recipe.yaml
Labels: R

#1560 Update xz [emscripten-3.1.73]
  recipes/recipes_emscripten/xz/build.sh
  recipes/recipes_emscripten/xz/recipe.yaml
Labels: R, 3.1.73

#1567 Update fribidi [emscripten-3.1.73]
  recipes/recipes_emscripten/fribidi/build.sh
  recipes/recipes_emscripten/fribidi/emscripten.meson.cross
  recipes/recipes_emscripten/fribidi/recipe.yaml
Labels: R, 3.1.73

#1568 Update expat [emscripten-3.1.73]
  recipes/recipes_emscripten/expat/build.sh
  recipes/recipes_emscripten/expat/recipe.yaml
Labels: R, 3.1.73

#1572 Update pcre2 [emscripten-3.1.73]
  recipes/recipes_emscripten/pcre2/build.sh
  recipes/recipes_emscripten/pcre2/recipe.yaml
Labels: R, 3.1.73

#1631 Update r-base
  recipes/recipes_emscripten/r-base/patches/0014-Build-cairo-without-pthread.patch
  recipes/recipes_emscripten/r-base/recipe.yaml
Labels: R

#1634 Update CppInterOp to 1.5.0
  recipes/recipes_emscripten/cppinterop/build.sh
  recipes/recipes_emscripten/cppinterop/patches/__clang_Interpreter_SetValueNoAlloc.patch
  recipes/recipes_emscripten/cppinterop/patches/lld.patch
  recipes/recipes_emscripten/cppinterop/patches/new.patch
  recipes/recipes_emscripten/cppinterop/recipe.yaml
Labels: 3.1.73

#1635 Update cppinterop on 3.1.73 branch
  recipes/recipes_emscripten/cppinterop/patches/__clang_Interpreter_SetValueNoAlloc.patch
  recipes/recipes_emscripten/cppinterop/recipe.yaml
Labels: 3.1.73

#1451 Add recipe for xeus-r
  recipes/recipes_emscripten/xeus-r/build.sh
  recipes/recipes_emscripten/xeus-r/recipe.yaml
Labels: R

#1613 triggrt glpk
  recipes/recipes_emscripten/glpk/build.sh
  recipes/recipes_emscripten/glpk/recipe.yaml
Labels: 3.1.73

#1641 Update cockle_fs to emscripten 3.1.73
  recipes/recipes_emscripten/cockle_fs/build.sh
  recipes/recipes_emscripten/cockle_fs/recipe.yaml
Labels: 3.1.73

#1648 Update fontconfig [emscripten-3.1.73]
  recipes/recipes_emscripten/fontconfig/recipe.yaml
Labels: R, 3.1.73

#1651 Add r-yaml
  recipes/recipes_emscripten/r-yaml/recipe.yaml
Labels: R

#1653 Add r-xfun
  recipes/recipes_emscripten/r-xfun/recipe.yaml
Labels: R

#1652 Update coreutils to emscripten 3.1.73
  recipes/recipes_emscripten/coreutils/build.sh
  recipes/recipes_emscripten/coreutils/recipe.yaml
Labels: 3.1.73

#1650 gmp [3.1.73]
  recipes/recipes_emscripten/gmp/build.sh
  recipes/recipes_emscripten/gmp/recipe.yaml
Labels: 3.1.73

#1664 Update run_modularized to emscripten 3.1.73
  recipes/recipes/run_modularized/recipe.yaml
  recipes/recipes/run_modularized/run_modularized.js
Labels: 3.1.73

#1666 Update lua to emscripten 3.1.73
  recipes/recipes_emscripten/lua/CMakeLists.txt
  recipes/recipes_emscripten/lua/recipe.yaml
Labels: 3.1.73

#1667 Update tree to emscripten 3.1.73
  recipes/recipes_emscripten/tree/build.sh
  recipes/recipes_emscripten/tree/recipe.yaml
Labels: 3.1.73

#1668 boot-cpp [3.1.73]
  recipes/recipes_emscripten/boost-cpp/recipe.yaml
Labels: 3.1.73

#1671 Update grep to emscripten 3.1.73
  recipes/recipes_emscripten/grep/COPYING
  recipes/recipes_emscripten/grep/build.sh
  recipes/recipes_emscripten/grep/recipe.yaml
Labels: 3.1.73

#1679 Update ncurses to emsdk 3.1.73
  recipes/recipes_emscripten/ncurses/build.sh
  recipes/recipes_emscripten/ncurses/recipe.yaml
Labels: 3.1.73

#1680 Update vim to emscripten 3.1.73
  recipes/recipes_emscripten/vim/build.sh
  recipes/recipes_emscripten/vim/patches/0001-const-char-args.patch
  recipes/recipes_emscripten/vim/recipe.yaml
Labels: 3.1.73

#1686 Add r-cachem
  recipes/recipes_emscripten/r-cachem/recipe.yaml
Labels: R

#1696 crc32c [3.1.73]
  recipes/recipes_emscripten/crc32c/build.sh
  recipes/recipes_emscripten/crc32c/recipe.yaml
  recipes/recipes_emscripten/crc32c/test_crc32c.py
Labels: 3.1.73

#1736 raylib and others [3.1.73]
  recipes/recipes_emscripten/eventpp/build.sh
  recipes/recipes_emscripten/eventpp/recipe.yaml
  recipes/recipes_emscripten/raygui/build.sh
  recipes/recipes_emscripten/raygui/recipe.yaml
  recipes/recipes_emscripten/raylib/build.sh
  recipes/recipes_emscripten/raylib/recipe.yaml
Labels: 3.1.73

#1763 Add cppinterop as a run dependency for xeus-cpp [3.1.73]
  recipes/recipes_emscripten/xeus-cpp/recipe.yaml
Labels: 3.1.73

#1767 Update r-base
  recipes/recipes_emscripten/r-base/patches/0014-Build-cairo-without-pthread.patch
  recipes/recipes_emscripten/r-base/patches/0014-Set-cairo-as-default-bitmap-type.patch
  recipes/recipes_emscripten/r-base/recipe.yaml
Labels: R

#1784 print more info in version-ticker-bot
  emci/bot/bump_recipes_versions.py
Labels: bot

#1789 Add r-bit
  recipes/recipes_emscripten/r-bit/GPL-2
  recipes/recipes_emscripten/r-bit/recipe.yaml
Labels: R, 3.1.45

#1790 Add r-bit64
  recipes/recipes_emscripten/r-bit64/GPL-2
  recipes/recipes_emscripten/r-bit64/recipe.yaml
Labels: R, 3.1.45

#1791 Add r-tzdb
  recipes/recipes_emscripten/r-tzdb/recipe.yaml
Labels: R, 3.1.45

#1792 Add r-vroom
  recipes/recipes_emscripten/r-vroom/recipe.yaml
Labels: R, 3.1.45

#1793 Add r-readr
  recipes/recipes_emscripten/r-readr/recipe.yaml
Labels: R, 3.1.45

#1794 Add r-ggrepel
  recipes/recipes_emscripten/r-ggrepel/build.sh
  recipes/recipes_emscripten/r-ggrepel/patches/exceptions_impl.h
  recipes/recipes_emscripten/r-ggrepel/recipe.yaml
Labels: R, 3.1.45

#1795 Add r-haven
  recipes/recipes_emscripten/r-haven/recipe.yaml
Labels: R, 3.1.45

#1796 Add r-plyr
  recipes/recipes_emscripten/r-plyr/MIT
  recipes/recipes_emscripten/r-plyr/build.sh
  recipes/recipes_emscripten/r-plyr/patches/exceptions_impl.h
  recipes/recipes_emscripten/r-plyr/recipe.yaml
Labels: R, 3.1.45

#1797 Add r-sp
  recipes/recipes_emscripten/r-sp/GPL-3
  recipes/recipes_emscripten/r-sp/recipe.yaml
Labels: R, 3.1.45

#1814 Bump xproperty recipe [3.1.73]
  recipes/recipes_emscripten/xproperty/recipe.yaml
Labels: 3.1.73

#1811 Bump xsimd recipe [3.1.73]
  recipes/recipes_emscripten/xsimd/recipe.yaml
Labels: 3.1.73

#1813 Bump xwidgets recipe [3.1.73]
  recipes/recipes_emscripten/xwidgets/recipe.yaml
Labels: 3.1.73

#1812 Update xvega recipe [3.1.73]
  recipes/recipes_emscripten/xvega/recipe.yaml
Labels: 3.1.73

#1815 Update xsimd version in xtensor recipe [3.1.73]
  recipes/recipes_emscripten/xtensor/recipe.yaml
Labels: 3.1.73

#1816 Fix matplotlib 3.10.0 on emscripten 3.1.73 V2
  recipes/recipes_emscripten/matplotlib/build-base.sh
  recipes/recipes_emscripten/matplotlib/patches/static-cast.patch
  recipes/recipes_emscripten/matplotlib/recipe.yaml
  recipes/recipes_emscripten/matplotlib/test_import_matplotlib.py
Labels: 3.1.73

#1817 Rename conda_build_config.yaml to variant.yaml
  pixi.toml
Labels: 3.1.73

#1818 Update xeus-r
  recipes/recipes_emscripten/xeus-r/recipe.yaml
Labels: R, 3.1.45

#1823 tsl_unordered 3.1.73
  recipes/recipes_emscripten/tsl_ordered_map/recipe.yaml
Labels: 3.1.73

#1826 xplugin [3.1.73]
  recipes/recipes_emscripten/xplugin/recipe.yaml
Labels: 3.1.73

#1825 mpdecimal [3.1.73]
  recipes/recipes_emscripten/mpdecimal/recipe.yaml
Labels: 3.1.73

#1827 shapely [3.1.73]
  recipes/recipes_emscripten/shapely/recipe.yaml
Labels: 3.1.73

#1829 awkward-cpp [3.1.73]
  recipes/recipes_emscripten/awkward-cpp/recipe.yaml
Labels: 3.1.73

#1810 Update Symengine recipe [3.1.73]
  recipes/recipes_emscripten/symengine/build.sh
  recipes/recipes_emscripten/symengine/recipe.yaml
Labels: 3.1.73

#1831 Add r-dplyr to xeus-r
  recipes/recipes_emscripten/xeus-r/recipe.yaml
Labels: R, 3.1.45

#1832 python-symengine [3.1.73]
  recipes/recipes_emscripten/python-symengine/CMakeLists.txt
  recipes/recipes_emscripten/python-symengine/build.sh
  recipes/recipes_emscripten/python-symengine/recipe.yaml
Labels: 3.1.73

#1833 pyb2d [3.1.73]
  recipes/recipes_emscripten/pyb2d/build.sh
Labels: 3.1.73

#1834 Fix signature mismatches in r-stringi
  recipes/recipes_emscripten/r-stringi/build.sh
  recipes/recipes_emscripten/r-stringi/recipe.yaml
Labels: R, 3.1.45

#1835 Add more WASM_BIGINT to r-base
  recipes/recipes_emscripten/r-base/config.site
  recipes/recipes_emscripten/r-base/recipe.yaml
Labels: R, 3.1.45

#1836 Rebuild r-haven with bigint
  recipes/recipes_emscripten/r-haven/recipe.yaml
Labels: R, 3.1.45

#1837 Rebuild tzdb with bigint
  recipes/recipes_emscripten/r-tzdb/recipe.yaml
Labels: R, 3.1.45

#1838 Rebuild readr with bigint
  recipes/recipes_emscripten/r-readr/recipe.yaml
Labels: R, 3.1.45

#1839 Rebuild vroom with bigint
  recipes/recipes_emscripten/r-vroom/recipe.yaml
Labels: R, 3.1.45

#1840 Rebuild dplyr with bigint
  recipes/recipes_emscripten/r-dplyr/recipe.yaml
Labels: R, 3.1.45
