Repository emscripten-forge/recipes, pull requests merged in 2025-03, with the labels that each got.

#1946 Create typescript definition file for cockle_fs
  recipes/recipes_emscripten/cockle_fs/build.sh
  recipes/recipes_emscripten/cockle_fs/recipe.yaml
Labels: 3.1.73

#1979 Update xeus to 5.2.0
  recipes/recipes_emscripten/xeus/recipe.yaml
Labels: 3.1.73

#1990 Rebuild xeus-cpp on latest xeus
  recipes/recipes_emscripten/xeus-cpp/recipe.yaml
Labels: 3.1.73

#1993 Update r-mass from 7.3-61 to 7.3-65
  recipes/recipes_emscripten/r-mass/recipe.yaml
Labels: R, 3.1.45

#1994 Update cross-r-base
  recipes/recipes/cross-r-base_emscripten-wasm32/activate-cross-r-base.sh
  recipes/recipes/cross-r-base_emscripten-wasm32/recipe.yaml
Labels: R, 3.1.45

#1995 Update r-matrix from 1.7-1 to 1.7-2
  recipes/recipes_emscripten/r-matrix/recipe.yaml
Labels: R, 3.1.45

#1996 Update r-mgcv
  recipes/recipes_emscripten/r-mgcv/recipe.yaml
Labels: R, 3.1.45

#1998 Update r-plyr
  recipes/recipes_emscripten/r-plyr/build.sh
  recipes/recipes_emscripten/r-plyr/patches/exceptions_impl.h
  recipes/recipes_emscripten/r-plyr/recipe.yaml
Labels: R, 3.1.45

#1999 Update r-promises
  recipes/recipes_emscripten/r-promises/build.sh
  recipes/recipes_emscripten/r-promises/patches/exceptions_impl.h
  recipes/recipes_emscripten/r-promises/recipe.yaml
Labels: R, 3.1.45

#2002 Update r-purrr from 1.0.2 to 1.0.4
  recipes/recipes_emscripten/r-purrr/recipe.yaml
Labels: R, 3.1.45

#2003 Update r-rcpp from 1.0.13-1 to 1.0.14
  recipes/recipes_emscripten/r-rcpp/patches/0001-Disable-demangler.patch
  recipes/recipes_emscripten/r-rcpp/recipe.yaml
Labels: R, 3.1.45

#2004 Update r-readr
  recipes/recipes_emscripten/r-readr/recipe.yaml
Labels: R, 3.1.45

#2005 Update r-rlang
  recipes/recipes_emscripten/r-rlang/recipe.yaml
Labels: R, 3.1.45

#2006 Update r-sp from 2.1-4 to 2.2-0
  recipes/recipes_emscripten/r-sp/recipe.yaml
Labels: R, 3.1.45

#2007 Update r-stringi
  recipes/recipes_emscripten/r-stringi/recipe.yaml
Labels: R, 3.1.45

#2008 Update r-sys
  recipes/recipes_emscripten/r-sys/recipe.yaml
Labels: R, 3.1.45

#2009 Update r-tibble
  recipes/recipes_emscripten/r-tibble/recipe.yaml
Labels: R, 3.1.45

#2011 Update r-tidyr
  recipes/recipes_emscripten/r-tidyr/recipe.yaml
Labels: R, 3.1.45

#2012 Update r-tzdb
  recipes/recipes_emscripten/r-tzdb/recipe.yaml
Labels: R, 3.1.45

#2010 Add recipe for nano to emscripten-3.1.73 branch
  recipes/recipes_emscripten/nano/build.sh
  recipes/recipes_emscripten/nano/recipe.yaml
Labels: 3.1.73

#2013 Update r-utf8
  recipes/recipes_emscripten/r-utf8/recipe.yaml
Labels: R, 3.1.45

#2014 Update r-vctrs
  recipes/recipes_emscripten/r-vctrs/recipe.yaml
Labels: R, 3.1.45

#2015 Update r-vroom
  recipes/recipes_emscripten/r-vroom/recipe.yaml
Labels: R, 3.1.45

#2023 Update r-xfun from 0.50 to 0.51
  recipes/recipes_emscripten/r-xfun/recipe.yaml
Labels: R, 3.1.45

#2024 Update r-yaml
  recipes/recipes_emscripten/r-yaml/recipe.yaml
Labels: R, 3.1.45

#2028 Update llvm to 20.1.0
  recipes/recipes_emscripten/llvm/build.sh
  recipes/recipes_emscripten/llvm/patches/define_LLVM_ABI.patch
  recipes/recipes_emscripten/llvm/recipe.yaml
Labels: 3.1.73

#2063 Add r-bit64
  recipes/recipes_emscripten/r-bit64/GPL-2
  recipes/recipes_emscripten/r-bit64/recipe.yaml
Labels: R, 3.1.73

#2064 Add r-cli
  recipes/recipes_emscripten/r-cli/recipe.yaml
Labels: R, 3.1.73

#2065 Add r-colorspace
  recipes/recipes_emscripten/r-colorspace/recipe.yaml
Labels: R, 3.1.73

#2066 Add r-data.table
  recipes/recipes_emscripten/r-data.table/recipe.yaml
Labels: R, 3.1.73

#2067 Add r-digest
  recipes/recipes_emscripten/r-digest/recipe.yaml
Labels: R, 3.1.73

#2068 Add r-fansi
  recipes/recipes_emscripten/r-fansi/patches/0001-Ignore-custom-limit-checks.patch
  recipes/recipes_emscripten/r-fansi/recipe.yaml
Labels: R, 3.1.73

#2069 Add r-farver
  recipes/recipes_emscripten/r-farver/recipe.yaml
Labels: R, 3.1.73

#2070 Add r-fastmap
  recipes/recipes_emscripten/r-fastmap/recipe.yaml
Labels: R, 3.1.73

#2071 Add r-glue
  recipes/recipes_emscripten/r-glue/recipe.yaml
Labels: R, 3.1.73

#2073 Add r-jsonlite
  recipes/recipes_emscripten/r-jsonlite/recipe.yaml
Labels: R, 3.1.73

#2074 Add r-lattice
  recipes/recipes_emscripten/r-lattice/recipe.yaml
Labels: R, 3.1.73

#2078 Add r-magrittr
  recipes/recipes_emscripten/r-magrittr/recipe.yaml
Labels: R, 3.1.73

#2079 Add r-mass
  recipes/recipes_emscripten/r-mass/recipe.yaml
Labels: R, 3.1.73

#2080 Add r-mime
  recipes/recipes_emscripten/r-mime/GPL-2
  recipes/recipes_emscripten/r-mime/recipe.yaml
Labels: R, 3.1.73

#2082 Add r-rcpp
  recipes/recipes_emscripten/r-rcpp/GPL-2
  recipes/recipes_emscripten/r-rcpp/patches/0001-Disable-demangler.patch
  recipes/recipes_emscripten/r-rcpp/recipe.yaml
Labels: R, 3.1.73

#2084 Add r-rlang
  recipes/recipes_emscripten/r-rlang/recipe.yaml
Labels: R, 3.1.73

#2085 Add r-sp
  recipes/recipes_emscripten/r-sp/GPL-3
  recipes/recipes_emscripten/r-sp/recipe.yaml
Labels: R, 3.1.73

#2086 Add r-stringi
  recipes/recipes_emscripten/r-stringi/build.sh
  recipes/recipes_emscripten/r-stringi/recipe.yaml
Labels: R, 3.1.73

#2087 Add r-sys
  recipes/recipes_emscripten/r-sys/recipe.yaml
Labels: R, 3.1.73

#2089 Add r-utf8
  recipes/recipes_emscripten/r-utf8/recipe.yaml
Labels: R, 3.1.73

#2090 Add r-xfun
  recipes/recipes_emscripten/r-xfun/recipe.yaml
Labels: R, 3.1.73

#2091 Add r-yaml
  recipes/recipes_emscripten/r-yaml/recipe.yaml
Labels: R, 3.1.73

#2093 Add r-cachem
  recipes/recipes_emscripten/r-cachem/recipe.yaml
Labels: R, 3.1.73

#2095 Add r-hexbin
  recipes/recipes_emscripten/r-hexbin/GPL-2
  recipes/recipes_emscripten/r-hexbin/recipe.yaml
Labels: R, 3.1.73

#2096 Add r-htmltools
  recipes/recipes_emscripten/r-htmltools/recipe.yaml
Labels: R, 3.1.73

#2097 Add r-vctrs
  recipes/recipes_emscripten/r-vctrs/recipe.yaml
Labels: R, 3.1.73

#2098 Add r-tibble
  recipes/recipes_emscripten/r-tibble/recipe.yaml
Labels: R, 3.1.73

#2099 Add r-vroom
  recipes/recipes_emscripten/r-vroom/recipe.yaml
Labels: R, 3.1.73

#2100 Add r-readr
  recipes/recipes_emscripten/r-readr/recipe.yaml
Labels: R, 3.1.73

#2105 Add r-dplyr
  recipes/recipes_emscripten/r-dplyr/recipe.yaml
Labels: R, 3.1.73

#2106 Add r-purrr
  recipes/recipes_emscripten/r-purrr/recipe.yaml
Labels: R, 3.1.73

#2107 Add r-tidyr
  recipes/recipes_emscripten/r-tidyr/recipe.yaml
Labels: R, 3.1.73

#2108 Add r-later
  recipes/recipes_emscripten/r-later/patches/0001-Do-not-link-with-atomic-lib.patch
  recipes/recipes_emscripten/r-later/recipe.yaml
Labels: R, 3.1.73

#2109 Add r-promises
  recipes/recipes_emscripten/r-promises/recipe.yaml
Labels: R, 3.1.73

#2110 Add r-matrix
  recipes/recipes_emscripten/r-matrix/recipe.yaml
Labels: R, 3.1.73

#2111 Add r-mgcv
  recipes/recipes_emscripten/r-mgcv/recipe.yaml
Labels: R, 3.1.73

#2112 Add r-haven
  recipes/recipes_emscripten/r-haven/recipe.yaml
Labels: R, 3.1.73

#2113 Add r-ggrepel
  recipes/recipes_emscripten/r-ggrepel/recipe.yaml
Labels: R, 3.1.73

#2114 Add xeus-r
  recipes/recipes_emscripten/xeus-r/build.sh
  recipes/recipes_emscripten/xeus-r/recipe.yaml
Labels: R, 3.1.73

#2118 Qutip 5.1.1
  recipes/recipes_emscripten/qutip/build.sh
  recipes/recipes_emscripten/qutip/recipe.yaml
Labels: 3.1.73

#1865 Add xeus-javascript [3.1.73]
  recipes/recipes_emscripten/xeus-javascript/recipe.yaml
Labels: 3.1.73

#2138 spatialgeometry
  recipes/recipes_emscripten/spatialgeometry/recipe.yaml
  recipes/recipes_emscripten/spatialgeometry/test_spatialgeometry.py
Labels: 3.1.73
