Repository emscripten-forge/recipes, pull requests merged in 2025-04, with the labels that each got.

#2147 Update llvm to 20.1.2
  recipes/recipes_emscripten/llvm/build.sh
  recipes/recipes_emscripten/llvm/patches/LoadDynamicLibrary.patch
  recipes/recipes_emscripten/llvm/patches/define_LLVM_ABI.patch
  recipes/recipes_emscripten/llvm/recipe.yaml
Labels: 3.1.73

#2148 Build symengine as a shared object
  recipes/recipes_emscripten/symengine/build.sh
  recipes/recipes_emscripten/symengine/patches/shared.patch
  recipes/recipes_emscripten/symengine/recipe.yaml
Labels: 3.1.73

#2201 Add logos
  .github/workflows/build_docs.yaml
  README.md
  docs/assets/banner.png
  docs/assets/banner.svg
  docs/assets/font_ZenDots.ttf
  docs/assets/icon.png
  docs/assets/icon.svg
  docs/assets/icon_color.svg
  docs/assets/icon_color_dark.svg
  docs/assets/icon_dark.svg
  docs/assets/icon_dark_color.svg
  docs/assets/icon_dark_light.svg
  docs/assets/icon_light.svg
  docs/assets/icon_none_color.svg
  docs/assets/icon_none_dark.svg
  docs/assets/icon_none_light.svg
  docs/assets/logo.png
  docs/assets/logo.svg
  docs/index.md
  mkdocs.yml
Labels: documentation

#2287 Update llvm to 20.1.4
  recipes/recipes_emscripten/llvm/build.sh
  recipes/recipes_emscripten/llvm/patches/define_LLVM_ABI.patch
  recipes/recipes_emscripten/llvm/patches/enable_exception_handling.patch
  recipes/recipes_emscripten/llvm/patches/wasm-ld.patch
  recipes/recipes_emscripten/llvm/recipe.yaml
Labels: Automerge
