Repository emscripten-forge/recipes, pull requests merged in 2025-02, with the labels that each got.

#1847 Add Sparrow recipe [3.1.73]
  recipes/recipes_emscripten/sparrow/build.sh
  recipes/recipes_emscripten/sparrow/recipe.yaml
Labels: 3.1.73

#1852 Update nelson to emscripten 3.1.73
  recipes/recipes_emscripten/nelson/patches/0001-Diff-enableTrivial-is-non-const.patch
  recipes/recipes_emscripten/nelson/recipe.yaml
Labels: 3.1.73

#1870 Update libflang from 19.1.0.rc2 to 19.1.7
  recipes/recipes_emscripten/libflang/recipe.yaml
Labels: 3.1.45

#1871 Update libflang from 19.1.0.rc2 to 19.1.7
  recipes/recipes_emscripten/libflang/recipe.yaml
Labels: 3.1.73

#1877 Build pixman without threat support
  recipes/recipes_emscripten/pixman/build.sh
  recipes/recipes_emscripten/pixman/emscripten.meson.cross
  recipes/recipes_emscripten/pixman/patches/0001-disable-threads.patch
  recipes/recipes_emscripten/pixman/recipe.yaml
Labels: 3.1.73

#1878 Include pkgconfig file for lzo
  recipes/recipes_emscripten/lzo/recipe.yaml
Labels: 3.1.73

#1879 Add cairo
  recipes/recipes_emscripten/cairo/build.sh
  recipes/recipes_emscripten/cairo/recipe.yaml
Labels: 3.1.73

#1886 Add instructions to build R packages
  .github/workflows/build_docs.yaml
  .gitignore
  docs/README.md
  docs/development/adding_packages.md
  pixi.toml
Labels: documentation

#1926 Remove pre.js in r-base
  recipes/recipes_emscripten/r-base/config.site
  recipes/recipes_emscripten/r-base/pre.js
  recipes/recipes_emscripten/r-base/recipe.yaml
Labels: R, 3.1.45

#1931 Rebuild ncurses against correct version
  recipes/recipes_emscripten/ncurses/recipe.yaml
Labels: 3.1.73

#1932 vim: use correct ncurses and terminfo
  recipes/recipes_emscripten/vim/build.sh
  recipes/recipes_emscripten/vim/recipe.yaml
Labels: 3.1.73

#1933 Update xeus-r from 0.4.0 to 0.5.0
  recipes/recipes_emscripten/xeus-r/build.sh
  recipes/recipes_emscripten/xeus-r/recipe.yaml
Labels: R, 3.1.45

#1934 Add cross-r-base package for emscripten
  recipes/recipes/cross-r-base_emscripten-wasm32/LICENSE
  recipes/recipes/cross-r-base_emscripten-wasm32/activate-cross-r-base.sh
  recipes/recipes/cross-r-base_emscripten-wasm32/build.sh
  recipes/recipes/cross-r-base_emscripten-wasm32/deactivate-cross-r-base.sh
  recipes/recipes/cross-r-base_emscripten-wasm32/recipe.yaml
Labels: R, 3.1.45

#1935 Update r-askpass
  recipes/recipes_emscripten/r-askpass/recipe.yaml
Labels: R, 3.1.45

#1936 Update r-base64enc
  recipes/recipes_emscripten/r-base64enc/recipe.yaml
Labels: R, 3.1.45

#1937 Update r-bit
  recipes/recipes_emscripten/r-bit/recipe.yaml
Labels: R, 3.1.45

#1938 Update cross-r-base
  recipes/recipes/cross-r-base_emscripten-wasm32/activate-cross-r-base.sh
  recipes/recipes/cross-r-base_emscripten-wasm32/recipe.yaml
Labels: R, 3.1.45

#1939 Update r-bit64
  recipes/recipes_emscripten/r-bit64/recipe.yaml
Labels: R, 3.1.45

#1940 Update r-cachem
  recipes/recipes_emscripten/r-cachem/recipe.yaml
Labels: R, 3.1.45

#1941 Update r-cli from 3.6.3 to 3.6.4
  recipes/recipes_emscripten/r-cli/recipe.yaml
Labels: R, 3.1.45

#1942 Update r-colorspace
  recipes/recipes_emscripten/r-colorspace/recipe.yaml
Labels: R, 3.1.45

#1947 Update r-data.table from 1.16.4 to 1.17.0
  recipes/recipes_emscripten/r-data.table/recipe.yaml
Labels: R, 3.1.45

#1948 Update r-digest
  recipes/recipes_emscripten/r-digest/recipe.yaml
Labels: R, 3.1.45

#1949 Update r-ellipsis
  recipes/recipes_emscripten/r-ellipsis/recipe.yaml
Labels: R, 3.1.45

#1950 Update r-fansi
  recipes/recipes_emscripten/r-fansi/recipe.yaml
Labels: R, 3.1.45

#1951 Update r-dplyr
  recipes/recipes_emscripten/r-dplyr/recipe.yaml
Labels: R, 3.1.45

#1952 Update r-farver
  recipes/recipes_emscripten/r-farver/recipe.yaml
Labels: R, 3.1.45

#1953 Update r-fastmap
  recipes/recipes_emscripten/r-fastmap/recipe.yaml
Labels: R, 3.1.45

#1954 Update r-ggrepel
  recipes/recipes_emscripten/r-ggrepel/build.sh
  recipes/recipes_emscripten/r-ggrepel/recipe.yaml
Labels: R, 3.1.45

#1955 Update r-glue from 1.7.0 to 1.8.0
  recipes/recipes_emscripten/r-glue/recipe.yaml
Labels: R, 3.1.45

#1957 Update r-htmltools
  recipes/recipes_emscripten/r-htmltools/recipe.yaml
Labels: R, 3.1.45

#1959 Update r-jsonlite from 1.8.9 to 1.9.0
  recipes/recipes_emscripten/r-jsonlite/recipe.yaml
Labels: R, 3.1.45

#1960 Update r-later
  recipes/recipes_emscripten/r-later/build.sh
  recipes/recipes_emscripten/r-later/recipe.yaml
Labels: R, 3.1.45

#1962 Update r-lazyeval
  recipes/recipes_emscripten/r-lazyeval/recipe.yaml
Labels: R, 3.1.45

#1963 Update r-magrittr
  recipes/recipes_emscripten/r-magrittr/recipe.yaml
Labels: R, 3.1.45
